#!/bin/bash
#title           : dmenu_shutdown
#description     : A simple dmenu call to logout, hibernate, shutdown, sleep, or restart 
#author      : Arne Küderle
#date            : 201602
#notes           : Install dmenu to use this script. For the best experience create a hotkey

#
# Edited by GG
#

actions=("logout\nrestart\nshutdown\nlock\nsuspend")
action=$(echo -e $actions | dmenu)
case "$action" in
    logout)
        pkill dwm
        ;;
        
    restart)
        systemctl reboot
        ;;

    shutdown)
        systemctl poweroff
        
        ;;

    lock)
        slock && $HOME/.local/bin/dwm_refresh_status.sh
        ;;

    suspend)
        $HOME/.local/bin/suspend.sh && $HOME/.local/bin/dwm_refresh_status.sh
        ;;
esac

# link to repo original repo: https://github.com/AKuederle/dmenu_tools
# link to Gabriel de Brito's version: https://github.com/gioiacyberpunk/dotfiles
