#!/usr/bin/sh

PAGE=$(cat ~/.config/qutebrowser/quickmarks | awk '{print substr($1, 0)}' | dmenu)
if [ "$PAGE" != "" ] 
then 
	qutebrowser $(grep $PAGE ~/.config/qutebrowser/quickmarks | awk '{print substr($2, 0)}')
fi
